#index:
#    path: /
#    controller: App\Controller\DefaultController::index

accueil:
    path: /accueil
    controller: App\Controller\AccueilController::index

connexion:
    path: /connexion
    controller: App\Controller\ConnexionController::index

connecter:
    path: /connecter
    controller: App\Controller\ConnexionController::connecter

visiteur:
    path: /visiteur
    controller: App\Controller\VisiteurController::index

consulterFicheFrais:
    path: /visiteur/consulterFicheFrais
    controller: App\Controller\VisiteurController::consulterFicheFrais

renseignerFicheFrais:
    path: /visiteur/renseignerFicheFrais
    controller: App\Controller\VisiteurController::renseignerFicheFrais

comptable:
    path: /comptable
    controller: App\Controller\ComptableController::index